name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -e .
      - name: Check formatting with ruff format
        run: |
          ruff format --check
      - name: Lint with ruff check
        run: |
          ruff check
      - name: Check typing with mypy
        run: |
          mypy src/ tests/
      - name: Test with pytest
        run: |
          pytest --hypothesis-profile ci
      # Very basic checks that we can execute the cmd-tool.
      - name: Execute papass --help
        run: |
          papass --help
      - name: Execute papass -c N -w WORDLIST
        run: |
          echo -e "foo\nbar\nbaz" > words.txt
          papass -c 2 -w words.txt
